### ISSUE TITLE
how do I use it?

### ISSUE THREAD

**Issue by Kesler031** [CassianoBelniak/vitral-game-card-templating#9]
After installing the program and the interface opens, I have only 3 buttons I can click on: Projects, New Project and Load project. The Projects buttons doesn't do anything and since I haven't created any .vitrals, I have no use for the other buttons either. I've tried both the installer and the .exe versions.

**Comment by CassianoBelniak** [comment]
You should be able to create a new project using the "New project" button, but I see why you are confused about that.

The main action in the New Project file picker is "Open", but it should be "Create" instead. Also, I think a default name should be suggested too instead of being blank.

I will see if I can change that.

In the mean time you should be able to create a new project by the "New project" button even if the message is suggesting that you need to open a existing one.

**Comment by CassianoBelniak** [comment]
Fixed in v1.1.1.

Now the file picker shows the correct dialog when creating a new project.
